# Generated by Django 4.0.3 on 2022-03-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceswitch',
            name='description',
            field=models.TextField(default='...', max_length=500),
        ),
        migrations.AlterField(
            model_name='deviceswitch',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
